//! Turns a `banto_core::ListParams` into `WHERE` / `ORDER BY` /
//! `LIMIT .. OFFSET ..` SQL appended onto a `sqlx::QueryBuilder`.
//!
//! This is the security-sensitive core of the storage layer: field names
//! coming from the frontend are **only ever** resolved through a
//! [`ColumnMap`] whitelist built by the service layer, and every value is
//! bound as a query parameter (never interpolated into the SQL string).
//!
//! - Sorting by an unknown field is silently skipped (a client asking to
//!   sort by a field that doesn't exist is not an error worth surfacing).
//! - Filtering by an unknown field is a hard `Err(BantoError::Other(_))`
//!   (bad request) since silently ignoring a filter could return more rows
//!   than the caller expects.
//!
//! A single generic implementation over `sqlx::Database` fights sqlx's
//! trait bounds hard enough (see the module-level discussion in the spec
//! doc, §12) that this module instead uses a `macro_rules!` to instantiate
//! one concrete, monomorphic implementation per backend (`Sqlite`,
//! `Postgres`), each gated behind its crate feature. The macro expands to
//! plain, independently type-checked code for each backend - no fighting
//! `Type<DB>`/`Encode<'_, DB>` bounds across an abstract `DB` type
//! parameter.

use std::collections::HashMap;

use banto_core::{
    BantoError, FilterOp, FilterState, ListParams, Pagination, SortDirection, SortState,
};
use serde_json::Value;

/// Whitelist mapping a wire field name (as sent by the frontend) to the
/// actual SQL column name. Built once per resource/service; field names not
/// present here can never reach raw SQL.
#[derive(Debug, Clone, Default)]
pub struct ColumnMap {
    columns: HashMap<String, String>,
}

impl ColumnMap {
    pub fn new() -> Self {
        Self {
            columns: HashMap::new(),
        }
    }

    /// Register `field` (wire name) -> `sql_column` (actual SQL column).
    pub fn column(mut self, field: &str, sql_column: &str) -> Self {
        self.columns
            .insert(field.to_string(), sql_column.to_string());
        self
    }

    /// Resolve a wire field name to its SQL column name, if whitelisted.
    pub fn resolve(&self, field: &str) -> Option<&str> {
        self.columns.get(field).map(String::as_str)
    }
}

/// Escape `%`, `_`, and `\` for use inside a `LIKE ... ESCAPE '\'` pattern.
fn escape_like(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '%' => out.push_str("\\%"),
            '_' => out.push_str("\\_"),
            _ => out.push(c),
        }
    }
    out
}

/// Render a `serde_json::Value` filter operand as a string for LIKE
/// patterns (numbers/bools get their natural string form; anything else is
/// rejected by the caller before this is reached).
fn value_as_like_operand(value: &Value) -> Result<String, BantoError> {
    match value {
        Value::String(s) => Ok(s.clone()),
        Value::Number(n) => Ok(n.to_string()),
        Value::Bool(b) => Ok(b.to_string()),
        other => Err(BantoError::Other(format!(
            "unsupported filter value for text match: {other}"
        ))),
    }
}

macro_rules! impl_list_query {
    ($module:ident, $db:ty) => {
        /// Backend-specific `ListParams` -> SQL implementation. See the
        /// module docs for why this is generated by a macro rather than a
        /// single generic function.
        pub mod $module {
            use super::*;
            use sqlx::QueryBuilder;

            /// Append `WHERE ... ORDER BY ... LIMIT ... OFFSET ...` for
            /// `params` onto `builder`. Field names are resolved only
            /// through `columns` (whitelist).
            pub fn apply_list_params(
                builder: &mut QueryBuilder<'_, $db>,
                columns: &ColumnMap,
                params: &ListParams,
            ) -> Result<(), BantoError> {
                append_where(builder, columns, &params.filters)?;
                append_order_by(builder, columns, &params.sort);
                append_pagination(builder, params.pagination);
                Ok(())
            }

            /// Append only the `WHERE` clause (used by services that need
            /// a separate `COUNT(*)` query sharing the same filters).
            pub fn append_where(
                builder: &mut QueryBuilder<'_, $db>,
                columns: &ColumnMap,
                filters: &[FilterState],
            ) -> Result<(), BantoError> {
                if filters.is_empty() {
                    return Ok(());
                }
                builder.push(" WHERE ");
                let mut first = true;
                for filter in filters {
                    let column = columns.resolve(&filter.field).ok_or_else(|| {
                        BantoError::Other(format!("unknown filter field: {}", filter.field))
                    })?;
                    if !first {
                        builder.push(" AND ");
                    }
                    first = false;
                    push_condition(builder, column, filter)?;
                }
                Ok(())
            }

            /// Append only the `ORDER BY` clause. Unknown fields are
            /// silently skipped (spec: sorting by an unknown field is not
            /// an error).
            pub fn append_order_by(
                builder: &mut QueryBuilder<'_, $db>,
                columns: &ColumnMap,
                sort: &[SortState],
            ) {
                let resolved: Vec<(&str, SortDirection)> = sort
                    .iter()
                    .filter_map(|s| columns.resolve(&s.field).map(|col| (col, s.direction)))
                    .collect();
                if resolved.is_empty() {
                    return;
                }
                builder.push(" ORDER BY ");
                for (i, (col, dir)) in resolved.iter().enumerate() {
                    if i > 0 {
                        builder.push(", ");
                    }
                    builder.push(*col);
                    builder.push(match dir {
                        SortDirection::Asc => " ASC",
                        SortDirection::Desc => " DESC",
                    });
                }
            }

            /// Append only `LIMIT .. OFFSET ..` (no-op when `pagination`
            /// is `None`).
            pub fn append_pagination(
                builder: &mut QueryBuilder<'_, $db>,
                pagination: Option<Pagination>,
            ) {
                if let Some(p) = pagination {
                    builder.push(" LIMIT ");
                    builder.push_bind(p.limit as i64);
                    builder.push(" OFFSET ");
                    builder.push_bind(p.offset as i64);
                }
            }

            fn push_condition(
                builder: &mut QueryBuilder<'_, $db>,
                column: &str,
                filter: &FilterState,
            ) -> Result<(), BantoError> {
                match filter.op {
                    FilterOp::Eq => push_binop(builder, column, "=", &filter.value)?,
                    FilterOp::Ne => push_binop(builder, column, "<>", &filter.value)?,
                    FilterOp::Lt => push_binop(builder, column, "<", &filter.value)?,
                    FilterOp::Lte => push_binop(builder, column, "<=", &filter.value)?,
                    FilterOp::Gt => push_binop(builder, column, ">", &filter.value)?,
                    FilterOp::Gte => push_binop(builder, column, ">=", &filter.value)?,
                    FilterOp::Contains => push_like(builder, column, &filter.value, true, true)?,
                    FilterOp::StartsWith => push_like(builder, column, &filter.value, false, true)?,
                    FilterOp::In => push_in(builder, column, &filter.value)?,
                    FilterOp::IsNull => {
                        builder.push(column);
                        builder.push(" IS NULL");
                    }
                    FilterOp::NotNull => {
                        builder.push(column);
                        builder.push(" IS NOT NULL");
                    }
                }
                Ok(())
            }

            fn push_binop(
                builder: &mut QueryBuilder<'_, $db>,
                column: &str,
                op: &str,
                value: &Value,
            ) -> Result<(), BantoError> {
                builder.push(column);
                builder.push(" ");
                builder.push(op);
                builder.push(" ");
                bind_value(builder, value)?;
                Ok(())
            }

            fn bind_value(
                builder: &mut QueryBuilder<'_, $db>,
                value: &Value,
            ) -> Result<(), BantoError> {
                match value {
                    Value::String(s) => {
                        builder.push_bind(s.clone());
                    }
                    Value::Bool(b) => {
                        builder.push_bind(*b);
                    }
                    Value::Number(n) => {
                        if let Some(i) = n.as_i64() {
                            builder.push_bind(i);
                        } else if let Some(f) = n.as_f64() {
                            builder.push_bind(f);
                        } else {
                            return Err(BantoError::Other(
                                "invalid numeric filter value".to_string(),
                            ));
                        }
                    }
                    other => {
                        return Err(BantoError::Other(format!(
                            "unsupported filter value: {other}"
                        )));
                    }
                }
                Ok(())
            }

            /// `contains`/`starts_with`: case-insensitive `LIKE`, matched
            /// value escaped for `%`/`_`/`\`. `prefix_wildcard` adds a
            /// leading `%` (contains only); `suffix_wildcard` adds a
            /// trailing `%` (both contains and starts_with).
            fn push_like(
                builder: &mut QueryBuilder<'_, $db>,
                column: &str,
                value: &Value,
                prefix_wildcard: bool,
                suffix_wildcard: bool,
            ) -> Result<(), BantoError> {
                let raw = value_as_like_operand(value)?;
                let escaped = escape_like(&raw);
                let mut pattern = String::with_capacity(escaped.len() + 2);
                if prefix_wildcard {
                    pattern.push('%');
                }
                pattern.push_str(&escaped);
                if suffix_wildcard {
                    pattern.push('%');
                }
                builder.push("LOWER(");
                builder.push(column);
                builder.push(") LIKE LOWER(");
                builder.push_bind(pattern);
                builder.push(") ESCAPE '\\'");
                Ok(())
            }

            /// `in`: binds every element of the array. An empty array is a
            /// clause that can never match (`1=0`), matching the semantics
            /// of "value is in the empty set" being always false.
            fn push_in(
                builder: &mut QueryBuilder<'_, $db>,
                column: &str,
                value: &Value,
            ) -> Result<(), BantoError> {
                let items = match value {
                    Value::Array(items) => items,
                    other => {
                        return Err(BantoError::Other(format!(
                            "'in' filter requires an array value, got: {other}"
                        )));
                    }
                };
                if items.is_empty() {
                    builder.push("1=0");
                    return Ok(());
                }
                builder.push(column);
                builder.push(" IN (");
                for (i, item) in items.iter().enumerate() {
                    if i > 0 {
                        builder.push(", ");
                    }
                    bind_value(builder, item)?;
                }
                builder.push(")");
                Ok(())
            }
        }
    };
}

#[cfg(feature = "sqlite")]
impl_list_query!(sqlite, sqlx::Sqlite);

#[cfg(feature = "postgres")]
impl_list_query!(postgres, sqlx::Postgres);

#[cfg(all(test, feature = "sqlite"))]
mod tests {
    use super::sqlite::apply_list_params;
    use super::*;
    use banto_core::Pagination;
    use serde_json::json;
    use sqlx::sqlite::SqlitePoolOptions;
    use sqlx::{Executor, QueryBuilder, Row, SqlitePool};

    async fn setup() -> SqlitePool {
        let pool = SqlitePoolOptions::new()
            .connect("sqlite::memory:")
            .await
            .expect("connect in-memory sqlite");
        pool.execute(
            "CREATE TABLE widgets (\
                id INTEGER PRIMARY KEY, \
                name TEXT NOT NULL, \
                price REAL NOT NULL, \
                active INTEGER NOT NULL\
            )",
        )
        .await
        .expect("create table");

        let rows: &[(i64, &str, f64, i64)] = &[
            (1, "Alpha Widget", 10.0, 1),
            (2, "Beta Widget", 20.0, 0),
            (3, "100% Off Widget", 5.0, 1),
            (4, "gamma_widget", 30.0, 1),
            (5, "Delta", 15.0, 0),
        ];
        for (id, name, price, active) in rows {
            sqlx::query("INSERT INTO widgets (id, name, price, active) VALUES (?, ?, ?, ?)")
                .bind(id)
                .bind(*name)
                .bind(price)
                .bind(active)
                .execute(&pool)
                .await
                .expect("insert row");
        }
        pool
    }

    fn columns() -> ColumnMap {
        ColumnMap::new()
            .column("id", "id")
            .column("name", "name")
            .column("price", "price")
            .column("active", "active")
    }

    async fn fetch_names(pool: &SqlitePool, params: &ListParams) -> Vec<String> {
        let mut builder = QueryBuilder::new("SELECT name FROM widgets");
        apply_list_params(&mut builder, &columns(), params).expect("apply params");
        let rows = builder
            .build()
            .fetch_all(pool)
            .await
            .expect("query should succeed");
        rows.into_iter().map(|r| r.get::<String, _>(0)).collect()
    }

    #[tokio::test]
    async fn eq_filters_by_bound_value() {
        let pool = setup().await;
        let params = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::Eq,
                value: json!("Alpha Widget"),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &params).await, vec!["Alpha Widget"]);
    }

    #[tokio::test]
    async fn ne_excludes_the_matching_row() {
        let pool = setup().await;
        let params = ListParams {
            filters: vec![FilterState {
                field: "active".to_string(),
                op: FilterOp::Ne,
                value: json!(1),
            }],
            ..Default::default()
        };
        let mut names = fetch_names(&pool, &params).await;
        names.sort();
        assert_eq!(names, vec!["Beta Widget", "Delta"]);
    }

    #[tokio::test]
    async fn lt_lte_gt_gte_compare_numerically() {
        let pool = setup().await;

        let lt = ListParams {
            filters: vec![FilterState {
                field: "price".to_string(),
                op: FilterOp::Lt,
                value: json!(10.0),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &lt).await, vec!["100% Off Widget"]);

        let lte = ListParams {
            filters: vec![FilterState {
                field: "price".to_string(),
                op: FilterOp::Lte,
                value: json!(10.0),
            }],
            ..Default::default()
        };
        let mut names = fetch_names(&pool, &lte).await;
        names.sort();
        assert_eq!(names, vec!["100% Off Widget", "Alpha Widget"]);

        let gt = ListParams {
            filters: vec![FilterState {
                field: "price".to_string(),
                op: FilterOp::Gt,
                value: json!(20.0),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &gt).await, vec!["gamma_widget"]);

        let gte = ListParams {
            filters: vec![FilterState {
                field: "price".to_string(),
                op: FilterOp::Gte,
                value: json!(20.0),
            }],
            ..Default::default()
        };
        let mut names = fetch_names(&pool, &gte).await;
        names.sort();
        assert_eq!(names, vec!["Beta Widget", "gamma_widget"]);
    }

    #[tokio::test]
    async fn contains_is_case_insensitive() {
        let pool = setup().await;
        let params = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::Contains,
                value: json!("WIDGET"),
            }],
            ..Default::default()
        };
        let mut names = fetch_names(&pool, &params).await;
        names.sort();
        assert_eq!(
            names,
            vec![
                "100% Off Widget",
                "Alpha Widget",
                "Beta Widget",
                "gamma_widget"
            ]
        );
    }

    #[tokio::test]
    async fn starts_with_anchors_the_prefix() {
        let pool = setup().await;
        let params = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::StartsWith,
                value: json!("alpha"),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &params).await, vec!["Alpha Widget"]);
    }

    /// A literal `%` in the data must only match when the query pattern
    /// escapes its own `%`; an unescaped LIKE would treat the data's `%` as
    /// a wildcard and this test would spuriously pass even without
    /// escaping. We assert both directions to prove the escaping is real.
    #[tokio::test]
    async fn like_escapes_percent_underscore_and_backslash_in_the_needle() {
        let pool = setup().await;

        // Literal '%' in the needle must match the literal '%' in "100% Off Widget"
        // and nothing else.
        let percent = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::Contains,
                value: json!("100%"),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &percent).await, vec!["100% Off Widget"]);

        // '_' is a single-char wildcard in SQL LIKE; escaped, it must only
        // match a literal underscore, not "gamma-widget"-style rows unless
        // they truly contain '_'.
        let underscore = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::Contains,
                value: json!("gamma_widget"),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &underscore).await, vec!["gamma_widget"]);

        // Without escaping, '_' would also match "gammaXwidget"-shaped names;
        // confirm a single-char substitution does NOT match.
        let would_match_if_unescaped = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::Contains,
                value: json!("gammaXwidget"),
            }],
            ..Default::default()
        };
        assert!(fetch_names(&pool, &would_match_if_unescaped)
            .await
            .is_empty());
    }

    #[tokio::test]
    async fn in_matches_any_bound_value() {
        let pool = setup().await;
        let params = ListParams {
            filters: vec![FilterState {
                field: "id".to_string(),
                op: FilterOp::In,
                value: json!([1, 3]),
            }],
            ..Default::default()
        };
        let mut names = fetch_names(&pool, &params).await;
        names.sort();
        assert_eq!(names, vec!["100% Off Widget", "Alpha Widget"]);
    }

    #[tokio::test]
    async fn in_with_empty_list_matches_nothing() {
        let pool = setup().await;
        let params = ListParams {
            filters: vec![FilterState {
                field: "id".to_string(),
                op: FilterOp::In,
                value: json!([]),
            }],
            ..Default::default()
        };
        assert!(fetch_names(&pool, &params).await.is_empty());
    }

    #[tokio::test]
    async fn is_null_and_not_null() {
        let pool = setup().await;
        // No NULLs in the fixture; is_null should match nothing and
        // not_null should match everything.
        let is_null = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::IsNull,
                value: json!(null),
            }],
            ..Default::default()
        };
        assert!(fetch_names(&pool, &is_null).await.is_empty());

        let not_null = ListParams {
            filters: vec![FilterState {
                field: "name".to_string(),
                op: FilterOp::NotNull,
                value: json!(null),
            }],
            ..Default::default()
        };
        assert_eq!(fetch_names(&pool, &not_null).await.len(), 5);
    }

    #[tokio::test]
    async fn sorts_by_multiple_keys_asc_and_desc() {
        let pool = setup().await;
        let params = ListParams {
            sort: vec![
                SortState {
                    field: "active".to_string(),
                    direction: SortDirection::Asc,
                },
                SortState {
                    field: "price".to_string(),
                    direction: SortDirection::Desc,
                },
            ],
            ..Default::default()
        };
        assert_eq!(
            fetch_names(&pool, &params).await,
            vec![
                "Beta Widget",
                "Delta",
                "gamma_widget",
                "Alpha Widget",
                "100% Off Widget"
            ]
        );
    }

    #[tokio::test]
    async fn pagination_and_total_count_pattern() {
        let pool = setup().await;
        let params = ListParams {
            sort: vec![SortState {
                field: "id".to_string(),
                direction: SortDirection::Asc,
            }],
            pagination: Some(Pagination {
                offset: 1,
                limit: 2,
            }),
            ..Default::default()
        };
        assert_eq!(
            fetch_names(&pool, &params).await,
            vec!["Beta Widget", "100% Off Widget"]
        );

        // The total_count pattern: a COUNT(*) query sharing the same WHERE
        // (built via `append_where`, not just ORDER BY/LIMIT/OFFSET)
        // reflects the pre-pagination count, while the paginated query
        // above only returns a page of it.
        let filtered = ListParams {
            filters: vec![FilterState {
                field: "active".to_string(),
                op: FilterOp::Eq,
                value: json!(1),
            }],
            pagination: Some(Pagination {
                offset: 0,
                limit: 1,
            }),
            ..Default::default()
        };
        let mut count_builder = QueryBuilder::new("SELECT COUNT(*) FROM widgets");
        super::sqlite::append_where(&mut count_builder, &columns(), &filtered.filters)
            .expect("append where");
        let total: i64 = count_builder
            .build_query_scalar()
            .fetch_one(&pool)
            .await
            .expect("count query");
        assert_eq!(total, 3);

        let rows = fetch_names(&pool, &filtered).await;
        assert_eq!(rows.len(), 1); // limited to 1 by pagination
    }

    #[tokio::test]
    async fn unknown_sort_field_is_silently_skipped() {
        let pool = setup().await;
        let params = ListParams {
            sort: vec![SortState {
                field: "does_not_exist".to_string(),
                direction: SortDirection::Asc,
            }],
            ..Default::default()
        };
        // No error, and no ORDER BY applied (rows come back in insertion order).
        assert_eq!(fetch_names(&pool, &params).await.len(), 5);
    }

    #[tokio::test]
    async fn unknown_filter_field_is_rejected() {
        let params = ListParams {
            filters: vec![FilterState {
                field: "does_not_exist".to_string(),
                op: FilterOp::Eq,
                value: json!(1),
            }],
            ..Default::default()
        };
        let mut builder = QueryBuilder::new("SELECT name FROM widgets");
        let result = apply_list_params(&mut builder, &columns(), &params);
        assert!(matches!(result, Err(BantoError::Other(_))));
    }
}
